services:
  app:
    build: .
    container_name: nestjs-divic-app
    ports:
      - '6000:3050'
    depends_on:
      - postgres
    env_file:
      - ./.env
    restart: unless-stopped
    command: yarn run start:prod

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432' # Expose PostgreSQL on host port of 5434
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist the PostgreSQL data

volumes:
  pgdata:
